# Generated by Django 5.2.3 on 2025-06-22 08:57

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reward_reflection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reflection',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='reflection',
            name='audio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AddField(
            model_name='reflection',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='text_reflection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='api.userprofile'),
        ),
    ]
